
### Testing of profile.js

POST http://localhost:3001/profile/create
Content-Type: application/json

{
  "email": "4@4",
  "password": "4",
  "phoneNumber": "234224456"
}

POST http://localhost:3001/profile/sign-in
Content-Type: application/json

{
  "email": "4@4",
  "password": "4"
}


POST http://localhost:3001/profile/generate-access-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9maWxlSUQiOjQsImlhdCI6MTc0NTM0NzM3NSwiZXhwIjoxNzQ1MzQ3OTc1fQ.-Uf5gZFPTycges7XjV01vAforijVntOHicqWyaZ8rD8"
}

POST http://localhost:3001/profile/get
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9maWxlSUQiOjMsImlhdCI6MTc0NTM0MjU1MCwiZXhwIjoxNzQ1MzQzMTUwfQ.rbIKSt9JeclXElV40AItR6rD-QLxhG9xdfrISavl90M"
}


POST http://localhost:3001/profile/modify
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9maWxlSUQiOjMsImlhdCI6MTc0NTM0MjU1MCwiZXhwIjoxNzQ1MzQzMTUwfQ.rbIKSt9JeclXElV40AItR6rD-QLxhG9xdfrISavl90M",
  "password": "2",
  "propertyName": "PhoneNumber",
  "newValue": "11114444"
}

POST http://localhost:3001/profile/delete
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9maWxlSUQiOjMsImlhdCI6MTc0NTM0MjU1MCwiZXhwIjoxNzQ1MzQzMTUwfQ.rbIKSt9JeclXElV40AItR6rD-QLxhG9xdfrISavl90M",
  "password": "2"
}

### Testing of productOrder.js

POST http://localhost:3001/productOrder/getProfileProductOrders
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9maWxlSUQiOjIsImlhdCI6MTc0NTM0MjY4NiwiZXhwIjoxNzQ1MzQzMjg2fQ.OSr6fJIsAeOD0DMFaxywKYZJO1G-mOy3Ds5Z1Erhd8k"
}

### Testing of vendor.js

POST http://localhost:3001/vendor/get
Content-Type: application/json

{
  "vendorID": "1"
}

POST http://localhost:3001/vendor/modify
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9maWxlSUQiOjIsImlhdCI6MTc0NTM0MjY4NiwiZXhwIjoxNzQ1MzQzMjg2fQ.OSr6fJIsAeOD0DMFaxywKYZJO1G-mOy3Ds5Z1Erhd8k",
  "password": "1",
  "propertyName": "Name",
  "newValue": "Lui Fendi Prada Designer"
}