
### Testing of profile.js

POST http://localhost:3001/profile/create
Content-Type: application/json

{
  "email": "1@1.com",
  "password": "1",
  "phoneNumber": "234224456"
}

POST http://localhost:3001/profile/sign-in
Content-Type: application/json

{
  "email": "1@1.com",
  "password": "1",
}

POST http://localhost:3001/profile/generate-access-token
Cookie: profileRefreshToken=

POST http://localhost:3001/profile/get
Cookie:  profileAccessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9maWxlSUQiOjQsImlhdCI6MTc0NTY0OTg5NiwiZXhwIjoxNzQ1NjUwMTk2fQ.W9gAxEdw6hBq5tON94-5EFemJTxd9Ms-UkJic04IQ3c

POST http://localhost:3001/profile/modify
Cookie:  profileAccessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9maWxlSUQiOjQsImlhdCI6MTc0NTY0OTg5NiwiZXhwIjoxNzQ1NjUwMTk2fQ.W9gAxEdw6hBq5tON94-5EFemJTxd9Ms-UkJic04IQ3c
Content-Type: application/json

{
  "password": "1",
  "propertyName": "PhoneNumber",
  "newValue": "11114444"
}

POST http://localhost:3001/profile/delete
Cookie:  profileAccessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9maWxlSUQiOjQsImlhdCI6MTc0NTY0OTg5NiwiZXhwIjoxNzQ1NjUwMTk2fQ.W9gAxEdw6hBq5tON94-5EFemJTxd9Ms-UkJic04IQ3c
Content-Type: application/json

{
  "password": "1"
}

### Testing of productOrder.js

POST http://localhost:3001/productOrder/getProfileProductOrders
Cookie:  profileAccessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9maWxlSUQiOjQsImlhdCI6MTc0NTY0OTg5NiwiZXhwIjoxNzQ1NjUwMTk2fQ.W9gAxEdw6hBq5tON94-5EFemJTxd9Ms-UkJic04IQ3c

### Testing of vendor.js

POST http://localhost:3001/vendor/get
Content-Type: application/json

{
  "vendorID": "1"
}

POST http://localhost:3001/vendor/modify
Cookie:  profileAccessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9maWxlSUQiOjQsImlhdCI6MTc0NTY0OTg5NiwiZXhwIjoxNzQ1NjUwMTk2fQ.W9gAxEdw6hBq5tON94-5EFemJTxd9Ms-UkJic04IQ3c

Content-Type: application/json

{
  "password": "1",
  "propertyName": "Name",
  "newValue": "Lui Fendi Prada Designer"
}